name: nodejs-payment-project
on: push
jobs: 
  first-job: 
   runs-on: ubuntu-latest
   steps: 
     - name: Git-checkout
       uses: actions/checkout@v4.1.7
     - name: Install nodejs
       run: | 
         npm ci
         npm run install
         npm fund
         npm audit fix
     - name: Build the payment nodejs app
       run : | 
         npm run build
  second-job: 
   needs: first-job
   runs-on: ubuntu-latest
   steps:
     - name: Git-checkout
       uses: actions/checkout@v4.1.7
     - name: Install docker
       uses: docker-practice/actions-setup-docker@v1
     - name: Build the docker images
       run: | 
         docker build -t nodejs:v2 .
         
