name: nodejs-payment-project
on: push
jobs: 
  first-job: 
   runs-on: ubuntu-latest
   steps: 
     - name: Git-checkout
       uses: actions/checkout@v4.1.7
     - name: Install nodejs
       run: |
         cd PaymentApp 
         npm install
         npm fund
         npm audit fix --force

  second-job: 
   needs: first-job
   runs-on: ubuntu-latest
   steps:
     - name: Git-checkout
       uses: actions/checkout@v4.1.7
     - name: Install docker
       uses:  docker-practice/actions-setup-docker@master
     - name: Build the docker images
       run: | 
         cd PaymentApp
         docker build -t nodejs:v2 .
         docker run -itd --name nodejs-server -p 3000:3000 nodejs:v2
         docker ps
         docker logs nodejs-server
         curl http://www.localhost.com:3000

         
